experimentName: LSTM_Autoencoder_Anomaly_Detection
trialConcurrency: 2
maxTrialNumber: 20
maxExperimentDuration: 2h

searchSpace:
  lstm_units_1:
    _type: choice
    _value: [32, 64, 128, 256]
  lstm_units_2:
    _type: choice
    _value: [16, 32, 64, 128]
  learning_rate:
    _type: loguniform
    _value: [0.0001, 0.01]
  batch_size:
    _type: choice
    _value: [32, 64, 128, 256]
  dropout_rate:
    _type: uniform
    _value: [0.0, 0.5]
  sequence_length:
    _type: choice
    _value: [10, 20, 30, 40]
  offset:
    _type: choice
    _value: [50, 100, 150, 200]

trialCommand: python trial.py
trialGpuNumber: 1

tuner:
  name: TPE
  classArgs:
    optimize_mode: minimize

assessor:
  name: Medianstop
  classArgs:
    optimize_mode: minimize
    start_step: 10

trainingService:
  platform: local
  useActiveGpu: true
  maxTrialNumberPerGpu: 1